project_id = "xejerqwyuvkbmhvqwepw"

[functions.copilot]
verify_jwt = false

[functions.nvidia-health]
verify_jwt = false

[functions.nemotron]
verify_jwt = false

[functions.dataverse]
verify_jwt = false

[functions.copilot-evaluate]
verify_jwt = false

[functions.weather-alerts]
verify_jwt = false